### PR TITLE
Fix #41 kafka configurationlost

### LINKED ISSUE #41: Consumer configuration lost
##### **Overview of the issue**
when i use the module to generate Producer & Consumer, it works fine, but when in a step 2 i want to generate only producers for example, all properties are removed from application.yml and the final application doesn't work anymore . 

here the message from the terminal.
```bash
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jhiOrderConsumer' defined in file [/home/monxxi/app/kafka/kafka-test-newGeneration/target/classes/test/kafka/msng/service/kafka/consumer/JhiOrderConsumer.class]: Unexpected exception during bean creation; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'kafka.consumer.jhiOrder.name' in value "${kafka.consumer.jhiOrder.name}"
```

First step : when i chose producer&consumer, the application.yml part generated is this one.
```yaml
kafka:
  '[bootstrap.servers]': localhost:9092
  consumer:
    jhiOrder:
      name: jhi-order-topic
      enabled: true
      '[key.deserializer]': org.apache.kafka.common.serialization.StringDeserializer
      '[value.deserializer]': test.kafka.msng.service.kafka.deserializer.JhiOrderDeserializer
      '[group.id]': jhipkafn-g
      '[auto.offset.reset]': earliest
    jhiProduct:
      name: jhi-product-topic
      enabled: true
      '[key.deserializer]': org.apache.kafka.common.serialization.StringDeserializer
      '[value.deserializer]': test.kafka.msng.service.kafka.deserializer.JhiProductDeserializer
      '[group.id]': jhipkafn-g
      '[auto.offset.reset]': earliest
  producer:
    jhiOrder:
      name: jhi-order-topic
      enabled: true
      '[key.serializer]': org.apache.kafka.common.serialization.StringSerializer
      '[value.serializer]': test.kafka.msng.service.kafka.serializer.JhiOrderSerializer
    jhiProduct:
      name: jhi-product-topic
      enabled: true
      '[key.serializer]': org.apache.kafka.common.serialization.StringSerializer
      '[value.serializer]': test.kafka.msng.service.kafka.serializer.JhiProductSerializer
```

and after using the module with only producer chosen, here the application.yml part newly generated. 

```yaml
kafka:
  '[bootstrap.servers]': localhost:9092
  
  producer:
    jhiOrder:
      name: jhi-order-topic
      enabled: true
      '[key.serializer]': org.apache.kafka.common.serialization.StringSerializer
      '[value.serializer]': test.kafka.msng.service.kafka.serializer.JhiOrderSerializer
    jhiProduct:
      name: jhi-product-topic
      enabled: true
      '[key.serializer]': org.apache.kafka.common.serialization.StringSerializer
      '[value.serializer]': test.kafka.msng.service.kafka.serializer.JhiProductSerializer
```

##### **Motivation for or Use Case**
it could be interesting to not override the full configuration but keep in memory, the producer & consumer already generated and adapt the final configuration according to the previous generation.

##### **Reproduce the error**
generate an app with the .yo-rc.json

use the module kafka `yo jhipster-kafka` to generate producer and consumer.

after reuse the module kafka  `yo jhipster-kafka` to generate only producer.

##### **JHipster Version(s)**
```
jhipkafn-g@0.0.0 /home/monxxi/app/kafka/kafka-test-newGeneration
└── generator-jhipster@6.8.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "test.kafka.msng",
      "nativeLanguage": "fr"
    },
    "jhipsterVersion": "6.8.0",
    "applicationType": "microservice",
    "baseName": "jhipkafnG",
    "packageName": "test.kafka.msng",
    "packageFolder": "test/kafka/msng",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": "kafka",
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "embeddableLaunchScript": false,
    "creationTimestamp": 1589537055990,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "clientPackageManager": "npm",
    "nativeLanguage": "fr",
    "languages": ["fr"],
    "blueprints": [],
    "skipClient": true,
    "skipUserManagement": true
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity JhiOrder {
  code Integer,
  name String
}
entity JhiProduct {
  name String,
  price BigDecimal
}
relationship ManyToMany {
  JhiProduct{jhiOrder} to JhiOrder{jhiProduct}
}

dto JhiOrder, JhiProduct with mapstruct
service JhiOrder, JhiProduct with serviceImpl
microservice JhiOrder, JhiProduct with jhipkafnG
clientRootFolder JhiOrder, JhiProduct with jhipkafnG

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Debian-3deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Debian-3deb10u1, mixed mode, sharing)

git version 2.20.1

node: v12.16.1

npm: 6.13.4

yeoman: 3.1.1

Docker version 19.03.8, build afacb8b7f0

docker-compose version 1.21.0, build unknown

- [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by monxxi**
Fix #41:
Adding a mechanism to permit to automatically preselect generator options based on the previous configuration read from the current application.yaml file of the application. 

Additional refacto: 
use an ejs template to generate the properties block

- Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/fdelbrayelle/generator-jhipster-kafka/actions) are green
- [ ] Tests are added where necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/fdelbrayelle/generator-jhipster-kafka/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

File: generators/app/index.js [hunk 1]
```diff
@@ -93,29 +96,51 @@ module.exports = class extends BaseGenerator {
                     .split('.')
                     .slice(0, -1)
                     .join('.')
-                    .match(/\w*$/i);
+                    .match(/\w*$/i)[0];
```
Comment (fdelbrayelle) [inline generators/app/index.js:99]: Why take only the first one?

File: generators/app/index.js [hunk 2]
```diff
@@ -134,12 +159,34 @@ module.exports = class extends BaseGenerator {
...
     writing() {
         // function to use directly template
         this.template = function(source, destination) {
             this.fs.copyTpl(this.templatePath(source), this.destinationPath(destination), this);
         };
 
+        // function generate kafka application properties
+        this.generateKafkaProperties = function() {
+            let kafkaPropertiesWithEjs;
+            jhipsterUtils.renderContent(this.templatePath('src/main/resources/application-subPartKafka.yml.ejs'), this, this, {}, res => {
```
Comment (fdelbrayelle) [inline generators/app/index.js:184]: We should keep only one `application.yml` and replace the `kafka:` block by the content of this file.

I would also replace the filename by `application-kafka.yml` even if it's temporary.

File: generators/app/index.js [hunk 3]
```diff
@@ -164,7 +211,11 @@ module.exports = class extends BaseGenerator {
         this.components = this.props.components;
         this.entities = this.props.entities;
         this.pollingTimeout = this.props.pollingTimeout;
-
+        // variable from previous states
+        /* //`${resourceDir}config/application.yml`
+        //`${testResourceDir}config/application.yml`
+        this.previousData = jsYaml.load(fsModule.readFileSync(`${resourceDir}config/application.yml`, 'utf8'));
+        this.log(this.previousData); */
```
Comment (fdelbrayelle) [inline generators/app/index.js:218]: Don't forget to remove those comment lines before to merge the PR

File: generators/app/index.js (hunk 1 above)
Comment (monxxi) [reply generators/app/index.js:99]: Because the result of the regex exécution is an object :
```javascript
[
  'JhiOrder',
  index: 37,
  input: 'src/main/java/test/kafka/msng/domain/JhiOrder',
  groups: undefined
]
```
But only the entity name is useful.

File: generators/app/index.js (hunk 3 above)
Comment (monxxi) [reply generators/app/index.js:218]: Yes, of course, it's still in progress :)

File: generators/app/index.js (hunk 2 above)
Comment (monxxi) [reply generators/app/index.js:184]: this method use the ejs file to generate a content that i store in a variable to assume the replacing in the application yaml file

File: generators/app/templates/src/main/resources/application-kafka.yml.ejs [hunk 4]
```diff
@@ -0,0 +1,37 @@
...
+<%_ } _%>
+<%_ if (components.includes('consumer')) { _%>
+  consumer:
+    <%_ for (entity of entities) { _%>
+    <%= _.camelCase(entity) _%>:
+      # This is a template topic naming convention which can be changed.
+      # %3Cmessage_type%3E.%3Capplication_name%3E.%3Centity_name%3E with (all in snake_case):
+      # - %3Cmessage_type%3E: queuing, logging, tracking, etl/db, streaming, push, user...
+      # - %3Capplication_name%3E: the application base name
+      # - %3Centity_name%3E: the entity name which is consumed
```
Comment (fdelbrayelle) [inline generators/app/templates/src/main/resources/application-kafka.yml.ejs:14]: As we are now using a template I would put this block only once just above `consumer:` at the same level just for information. What do you think?

You could replace `This is a template topic naming convention which can be changed.` by `There a topic naming convention below which can be changed.`

File: generators/app/index.js [hunk 5]
```diff
@@ -290,13 +300,10 @@ module.exports = class extends BaseGenerator {
...
                     `${javaDir}service/kafka/serializer/${entity}Serializer.java`
                 );
-
-                producersCpt++;
             }
         });
 
-        kafkaProperties += '\n';
-
+        const kafkaProperties = this.generateKafkaProperties();
```
Comment (fdelbrayelle) [inline generators/app/index.js:306]: You can put directly `this.generateKafkaProperties()` in the next line

Comment (fdelbrayelle) [reply generators/app/index.js:306]: Or even better remove lines 306 and 307 and `this.log` the returning value of the `generateKafkaProperties` function

File: generators/app/index.js [hunk 6]
```diff
@@ -134,12 +167,39 @@ module.exports = class extends BaseGenerator {
...
+                fsModule.readFileSync(`${jhipsterConstants.SERVER_MAIN_RES_DIR}config/application.yml`, 'utf8')
+            );
+            if (previousGlobalConfiguration && previousGlobalConfiguration.kafka) {
+                return previousGlobalConfiguration.kafka;
+            }
+        } catch (e) {
+            this.log(
+                `${chalk.red.bold(
+                    'WARN!'
+                )} Could not parse the previous kafka configuration, some previous configurations could be overwritten\n`
```
Comment (fdelbrayelle) [inline generators/app/index.js:182]: `Kafka` instead of `kafka` and `the previous configuration` instead `some previous configurations`?

File: generators/app/index.js [hunk 7]
```diff
@@ -94,28 +123,32 @@ module.exports = class extends BaseGenerator {
...
                     .join('.')
                     .match(/\w*$/i);
-                entitiesChoices.push({
-                    name: className,
-                    value: className
-                });
+                if (className) {
+                    entitiesChoices.push({
+                        name: className[0],
+                        value: className[0]
```
Comment (fdelbrayelle) [inline generators/app/index.js:129]: You should put only once the `[0]` on the `className` variable declaration

Comment (monxxi) [reply generators/app/index.js:129]: i want to test the result of the matcher in case of an undefined is returned before use it

File: generators/app/index.js (hunk 6 above)
Comment (monxxi) [reply generators/app/index.js:182]: Yes i gonna change it

File: generators/app/index.js (hunk 5 above)
Comment (monxxi) [reply generators/app/index.js:306]: i need the variable declaration for the usage in line 310 & 311
```javascript
 this.replaceContent(`${resourceDir}config/application.yml`, kafkaBlockPattern, kafkaProperties);
 this.replaceContent(`${testResourceDir}config/application.yml`, kafkaBlockPattern, kafkaProperties);
```

File: generators/app/index.js [hunk 8]
```diff
@@ -58,6 +61,32 @@ module.exports = class extends BaseGenerator {
         };
     }
 
+    extractDefaultPromptValues(previousKafkaConfiguration, possibleComponents) {
+        const transformToJavaClassNameCase = entityName => {
+            return _.upperFirst(_.camelCase(entityName));
+        };
```
Comment (fdelbrayelle) [inline generators/app/index.js:67]:
```suggestion
        const transformToJavaClassNameCase = _.upperFirst(_.camelCase(entityName));
```
